language: "python"
python: "2.7"
install:
  - "pip install --upgrade pip wheel"
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
script: 
  - python manage.py collectstatic
  - python manage.py test
after_success:
  - beeper build --version $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "dist/wikisensei-$TRAVIS_TAG.tgz"
  skip_cleanup: true
  on:
    tags: true
