# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wiki',
            unique_together=set([('user', 'title')]),
        ),
    ]
