# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20170414_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
