# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20170418_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='compiled',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='version',
            name='compiled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
