# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20170419_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='hash',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
